### ISSUE TITLE
an error occured while processing dictionary: std::bad_alloc

### ISSUE THREAD

**Issue by D1mon** [nongeneric/lsd2dsl#7] opened 2018-04-02 13:16 UTC
Установил на виртуалке (Manjaro).

**Comment by sepanko** [comment] 2018-07-08 09:33
I have the same error on Ubuntu 18.04.

**Comment by nongeneric** [comment] 2018-07-08 10:49
I can't reproduce the crash on my dictionaries. Do you mind sharing the problematic file?

**Comment by D1mon** [comment] 2018-07-08 11:19
lsd2dsl v0.3.0.r3.g08f0999-1

> an error occured while processing dictionary: boost::filesystem::create_directories: Invalid argument

`lsd2dsl --lsd /home/admin/Dictionary_kompjyuternyh_terminov_i_sokrascheniy_EnRu.lsd --out .`
The program does not understand the point (.) - the current folder.


[Dictionary_kompjyuternyh_terminov_i_sokrascheniy_EnRu.lsd.zip](https://github.com/nongeneric/lsd2dsl/files/2173658/Dictionary_kompjyuternyh_terminov_i_sokrascheniy_EnRu.lsd.zip)

Header:
  Version:  132001
  Headings: 479
  Source:   1033 (English)
  Target:   1049 (Russian)
  Name:     
an error occured while processing dictionary: std::bad_alloc

**Comment by sepanko** [comment] 2018-07-08 11:41
Georgian-Russian: [Ka-Ru_Kankava_Falb_v1_0.lsd.zip](https://github.com/nongeneric/lsd2dsl/files/2173666/Ka-Ru_Kankava_Falb_v1_0.lsd.zip)

`lsd2dsl --lsd Ka-Ru_Kankava_Falb_v1_0.lsd --out tmp`
```
Header:
  Version:  120001
  Headings: 20048
  Source:   1089 (Swahili)
  Target:   1049 (Russian)
  Name:     
an error occured while processing dictionary: std::bad_alloc
```
(ignore the misleading "Swahili", it's probably a mistake in the .lsd).

The Python [lsdreader](https://github.com/sv99/lsdreader) converts it successfully.

**Comment by nongeneric** [comment] 2018-07-08 21:29
Thank you both. Unfortunately those dictionary versions just aren't implemented.
The crash happened due to the incorrect error handling, which I now fixed, together with the handling of '.' in paths.
I'm not looking forward implementing more versions right now. There are tools already available for that.

**Closed** 2018-08-03 19:12 UTC
